image:
  repository: chromadb/chroma
  tag: 0.5.4

replicaCount: 2

service:
  name: chromadb
  port: 8000

persistence:
  enabled: true
  size: 20Gi
  storageClass: ""

resources:
  requests: { cpu: "500m", memory: "1Gi" }
  limits:   { cpu: "2",    memory: "4Gi" }

quota:
  enabled: true
  hard:
    requests.cpu: "8"
    requests.memory: "8Gi"
    limits.cpu: "16"
    limits.memory: "16Gi"
    pods: "30"

limits:
  enabled: true
  default:        { cpu: "2",  memory: "4Gi" }
  defaultRequest: { cpu: "500m", memory: "1Gi" }
